// AUTH
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const CLEAR_AUTH_SUCCESS_STATE = "CLEAR_AUTH_SUCCESS_STATE";
export const AUTH_FAIL = "AUTH_FAIL";
export const POST_ADDITIONAL_USER_INFO = "POST_ADDITIONAL_USER_INFO";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const CLEAR_ERROR = "CLEAR_ERROR";
// get additional user info
export const GET_ADDITIONAL_USER_INFO_START = "GET_ADDITIONAL_USER_INFO_START";
export const GET_ADDITIONAL_USER_INFO_SUCCESS = "GET_ADDITIONAL_USER_INFO_SUCCESS";
export const GET_ADDITIONAL_USER_INFO_FAILED = "GET_ADDITIONAL_USER_INFO_FAILED";
// delete user info
export const DELETE_ADDITIONAL_USER_INFO_START = "DELETE_ADDITIONAL_USER_INFO_START";
export const DELETE_ADDITIONAL_USER_INFO_SUCCESS = "DELETE_ADDITIONAL_USER_INFO_SUCCESS";
export const DELETE_ADDITIONAL_USER_INFO_FAILED = "DELETE_ADDITIONAL_USER_INFO_FAILED";
// post edited user info
export const POST_NEW_USER_INFO_START = "POST_NEW_USER_INFO_START";
export const POST_NEW_USER_INFO_SUCCESS = "POST_NEW_USER_INFO_SUCCESS";
export const POST_NEW_USER_INFO_FAILED = "POST_NEW_USER_INFO_FAILED";

// BOOKING TOUR
export const BOOK_TOUR_START = "BOOK_TOUR_START";
export const BOOK_TOUR_SUCCESS = "BOOK_TOUR_SUCCESS";
export const BOOK_TOUR_FAILED = "BOOK_TOUR_FAILED";
export const BOOK_CLEAR_ERROR = "BOOK_CLEAR_ERROR";

// FETCHING BOOKED TOURS FROM BACKEND
export const FETCH_TOURS_START = "FETCH_TOURS_START";
export const FETCH_TOURS_SUCCESS = "FETCH_TOURS_SUCCESS";
export const FETCH_TOURS_FAILED = "FETCH_TOURS_FAILED";

// DELETING BOOKED TOURS
export const DELETE_SINGLE_TOUR_SUCCESS = "DELETE_SINGLE_TOUR_SUCCESS";
export const DELETE_SINGLE_TOUR_FAILED = "DELETE_SINGLE_TOUR_FAILED";
// CLEAR ALL TOURS FROM TOURBOX
export const CLAER_TOURS_START = "CLAER_TOURS_START";
export const CLAER_TOURS_SUCCESS = "CLAER_TOURS_SUCCESS";
export const CLAER_TOURS_FAILED = "CLAER_TOURS_FAILED";
export const CLEAR_DELETE_TOUR_ERROR = "CLEAR_DELETE_TOUR_ERROR";

// REQUEST TOURS - reqesting and fetching
export const REQ_TOUR_START = "REQ_TOUR_START";
export const REQ_TOUR_SUCCESS = "REQ_TOUR_SUCCESS";
export const REQ_TOUR_FAILED = "REQ_TOUR_FAILED";
export const REQ_CLEAR_ERROR = "REQ_CLEAR_ERROR";
// deleting single req tour
export const REQ_TOUR_DELETE_SUCCESS = "REQ_TOUR_DELETE_SUCCESS";
export const REQ_TOUR_DELETE_FAILED = "REQ_TOUR_DELETE_FAILED";
// deleting all req tours
export const REQ_TOURS_CLEAR_ALL_START = "REQ_TOURS_CLEAR_ALL_START";
export const REQ_TOURS_CLEAR_ALL_SUCCESS = "REQ_TOURS_CLEAR_ALL_SUCCESS";
export const REQ_TOURS_CLEAR_ALL_FAILED = "REQ_TOURS_CLEAR_ALL_FAILED";
export const CLEAR_REQ_TOUR_DELETE_ERROR = "CLEAR_REQ_TOUR_DELETE_ERROR";

export const FETCH_REQ_TOURS_START = "FETCH_REQ_TOURS_START";
export const FETCH_REQ_TOURS_SUCCESS = "FETCH_REQ_TOURS_SUCCESS";
export const FETCH_REQ_TOURS_FAILED = "FETCH_REQ_TOURS_FAILED";
export const FETCH_REQ_TOURS_CLEAR_ERROR = "FETCH_REQ_TOURS_CLEAR_ERROR";

// REVIEWS
export const LEAVE_REVIEW_START = "LEAVE_REVIEW_START";
export const LEAVE_REVIEW_SUCCESS = "LEAVE_REVIEW_SUCCESS";
export const LEAVE_REVIEW_FAILED = "LEAVE_REVIEW_FAILED";
export const LEAVE_REVIEW_CLEAR_ERROR = "LEAVE_REVIEW_CLEAR_ERROR";

export const FETCH_AGENCY_REVIEW_START = "FETCH_AGENCY_REVIEW_START";
export const FETCH_AGENCY_REVIEW_SUCCESS = "FETCH_AGENCY_REVIEW_SUCCESS";
export const FETCH_AGENCY_REVIEW_FAILED = "FETCH_AGENCY_REVIEW_FAILED";

export const FETCH_TOUR_REVIEWS_START = "FETCH_TOUR_REVIEW_START";
export const FETCH_TOUR_REVIEWS_SUCCESS = "FETCH_TOUR_REVIEW_SUCCESS";
export const FETCH_TOUR_REVIEWS_FAILED = "FETCH_TOUR_REVIEW_FAILED";

// DELETING REVIEW
export const REMOVE_AGENCY_REVIEW_SUCCESS = "REMOVE_AGENCY_REVIEW_SUCCESS";
export const REMOVE_AGENCY_REVIEW_FAILED = "REMOVE_AGENCY_REVIEW_FAILED";

export const REMOVE_TOUR_REVIEW_SUCCESS = "REMOVE_TOUR_REVIEW_SUCCESS";
export const REMOVE_TOUR_REVIEW_FAILED = "REMOVE_TOUR_REVIEW_FAILED";

